[package]
name = "Simple-CaveGen-Rust"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.30.0"

[[bin]]
name = "Simple-CaveGen-Rust"
path = "main.rs"
